<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FUN_MergeLongStrings10" Id="{dbdb2318-c922-4e0b-bb1b-8c8938bfc66e}" SpecialFunc="None">
    <Declaration><![CDATA[(* 
:Description: This function is used to merge 10 long strings
*)
FUNCTION FUN_MergeLongStrings10 : STRING(2000)
VAR_INPUT
	sStr1	: STRING(2000);
	sStr2	: STRING(2000);
	sStr3	: STRING(2000);
	sStr4	: STRING(2000);
	sStr5	: STRING(2000);
	sStr6	: STRING(2000);
	sStr7	: STRING(2000);
	sStr8	: STRING(2000);
	sStr9	: STRING(2000);
	sStr10	: STRING(2000);
END_VAR
VAR
	sStrTemp1 :	STRING(2000);
	sStrTemp2 :	STRING(2000);
END_VAR
(*
Version history:

+-------------+------------+----------------+----------+------------------------------------------+
|Date         | Version    | created under  | Author   | Remark                                   |
+=============+============+================+==========+==========================================+
|2021-11      | 1.0.0.0    | V3.1.4024.22   | ADBO     | Function created		                  |
+-------------+------------+----------------+----------+------------------------------------------+

*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[CONCAT2(ADR(sStr1),ADR(sStr2),ADR(sStrTemp1),SIZEOF(sStrTemp1));
CONCAT2(ADR(sStrTemp1),ADR(sStr3),ADR(sStrTemp2),SIZEOF(sStrTemp2));
CONCAT2(ADR(sStrTemp2),ADR(sStr4),ADR(sStrTemp1),SIZEOF(sStrTemp1));
CONCAT2(ADR(sStrTemp1),ADR(sStr5),ADR(sStrTemp2),SIZEOF(sStrTemp2));
CONCAT2(ADR(sStrTemp2),ADR(sStr6),ADR(sStrTemp1),SIZEOF(sStrTemp1));
CONCAT2(ADR(sStrTemp1),ADR(sStr7),ADR(sStrTemp2),SIZEOF(sStrTemp2));
CONCAT2(ADR(sStrTemp2),ADR(sStr8),ADR(sStrTemp1),SIZEOF(sStrTemp1));
CONCAT2(ADR(sStrTemp1),ADR(sStr9),ADR(sStrTemp2),SIZEOF(sStrTemp2));
CONCAT2(ADR(sStrTemp2),ADR(sStr10),ADR(FUN_MergeLongStrings10),SIZEOF(FUN_MergeLongStrings10));]]></ST>
    </Implementation>
    <LineIds Name="FUN_MergeLongStrings10">
      <LineId Id="479" Count="7" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>