<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FUN_MergeStrings3" Id="{a7dc5695-0618-4375-a202-b8b45cf00675}" SpecialFunc="None">
    <Declaration><![CDATA[(* 
:Description: This function is used to merge 5 strings
*)
FUNCTION FUN_MergeStrings3 : STRING
VAR_INPUT
	sStr1	: STRING;			(* Fifth string in merge row *)
	sStr2	: STRING;			(* Fourth string in merge row *)
	sStr3	: STRING;			(* Fourth string in merge row *)

END_VAR
(*
Version history:

+-------------+------------+----------------+----------+------------------------------------------+
|Date         | Version    | created under  | Author   | Remark                                   |
+=============+============+================+==========+==========================================+
|2022-06      | 1.0.0.0    | V3.1.4024.22   | ADS      | Function created    		              |
+-------------+------------+----------------+----------+------------------------------------------+

*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FUN_MergeStrings3 := CONCAT(sStr1,sStr2);
FUN_MergeStrings3 := CONCAT(FUN_MergeStrings3,sStr3);
]]></ST>
    </Implementation>
    <LineIds Name="FUN_MergeStrings3">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>