<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ModbusMaster_Test" Id="{b7e169e6-23e0-47cc-bba5-b3ea5eb58bcc}" SpecialFunc="None">
    <Declaration><![CDATA[(* FB relate to Hardware *)
FUNCTION_BLOCK FB_ModbusMaster_Test EXTENDS FB_TestSuite
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ModbusMaster_Test">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>