<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_UniversalVFDModbus_Ex" Id="{525cf8e8-ff46-40d7-a282-18fc349596ed}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_UniversalVFDModbus_Ex EXTENDS FB_UniversalVFDModbus

]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
    <LineIds Name="FB_UniversalVFDModbus_Ex">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>